### ISSUE TITLE
Падает первый же тест на этапе отправки POST запроса с телом User.

### ISSUE THREAD

**Issue by toptun80** [toptun80/AQA-2.6_Netology-Home-Project#1]
### Шаги:
 - запустить @Test happyPathTest
### Ожидаемый результат:
 - тест Passed
### Фактический результат:
 - тест Failed с "NullPointerException: Cannot get property 'assertionClosure' on null object"
### Окружение: 
Windows 10 Pro, 
IntelliJ IDEA 2019.3.3 (Community Edition)

![2020-02-21_005450](https://user-images.githubusercontent.com/54706630/74982571-6c058880-5445-11ea-9430-b7d20abc4aee.jpg)

**Comment by coursar** [comment]
Вместо:
https://github.com/toptun80/AQA-2.6_Netology-Home-Project/blob/3fd98eef3664af397a0d2f842de4068727c4da9d/src/test/java/ru/netology/restassured/UserDataGenerator.java#L45-L51

Должно быть:
```java
given() // "дано"
                    .spec(requestSpec) // указываем, какую спецификацию используем
                    .body(userDataModel) // передаём в теле объект, который будет преобразован в JSON
                    .when() // "когда"
                    .post(new EndPoint().getEndPoint()) // на какой путь, относительно BaseUri отправляем запрос
                    .then() // "тогда ожидаем"
                    .statusCode(200); // код 200 OK
```

где `given()` - это статический импорт: `import static io.restassured.RestAssured.given;
`
